In [ ]:
import numpy.linalg as npl
import numpy as np

A = np.array(([15, -3, -1], [-3, 18, -6], [-4, -1, 12]))
b= np.array(([3800], [1200], [2350]))

I = npl.inv(A)

print("Matriz inversa ")
print(I)
print("Solução utilizando a matriz inversa ")
c = np.dot(I, b)
print("c = \n", c)

## x tem q dar 27,15 e 29,15%
x1 = I[0,0]*b[0] + I[0,1]*b[1] + I[0,2]*b[2]
novob3 = ((c[0]+10) -I[0,0]*b[0] - I[0,1]*b[1])/I[0,2]
x2 = I[1,0]*b[0] + I[1,1]*b[1] + I[1,2]*b[2]
x3 = I[2,0]*b[0] + I[2,1]*b[1] + I[2,2]*b[2]


print("\n")
print(novob3)
print(novob3/b[2])

Matriz inversa 
[[0.07253886 0.01278066 0.01243523]
 [0.02072539 0.06079447 0.03212435]
 [0.02590674 0.00932642 0.09015544]]
Solução utilizando a matriz inversa 
c = 
 [[320.20725389]
 [227.20207254]
 [321.50259067]]


[3154.16666667]
[1.34219858]


Aplicacao 2

In [ ]:
import numpy.linalg as npl
import numpy as np

A = np.array(([0.52, 0.30, 0.18], [0.20, 0.50, 0.30], [0.25, 0.20, 0.55]))

b= np.array(([4800], [5810], [5690]))

I = npl.inv(A)

print("Matriz invertida ")
print(I)
x = np.dot(I,b)
print("O engenheiro deve retirar as seguintes quantidades da Mina 1,2,3 respectivamente: \n", x)

#Respostas

novob1 = ((x[1]+1000)- I[1,1]*b[1]-I[1,2]*b[2])/I[1,0]

variacao = novob1/b[0]-1
print("\nSe retirarmos 1000 m3 a mais da mina 1, a nova quantidade de areia será: \n")
print(novob1)
print("\nO percentual de variacao foi de: \n")
print(variacao)

novob11 = ((x[0] + 1000) - I[0,1]*b[1] - I[0,2]*b[2])/I[0,0]

variacao2 = novob11/b[0]-1

print("\nSe retirarmos 1000 m3 a mais da mina 2, a nova quantidade de areia será: \n")
print(novob11)
print("\nO percentual de variacao foi de: \n")
print(variacao2)

Matriz invertida 
[[ 2.5        -1.5         0.        ]
 [-0.40697674  2.80232558 -1.39534884]
 [-0.98837209 -0.3372093   2.3255814 ]]
O engenheiro deve retirar as seguintes quantidades da Mina 1,2,3 respectivamente: 
 [[3285.        ]
 [6388.48837209]
 [6529.18604651]]

Se retirarmos 1000 m3 a mais da mina 1, a nova quantidade de areia será: 

[2342.85714286]

O percentual de variacao foi de: 

[-0.51190476]

Se retirarmos 1000 m3 a mais da mina 2, a nova quantidade de areia será: 

[5200.]

O percentual de variacao foi de: 

[0.08333333]
