Questão 1.

In [6]:
import numpy as np
import scipy.sparse.linalg as sp
import scipy.optimize as so

g = lambda c: (2*c)/(4 + 0.8*c + c**2 + 0.2*c**3)

f = lambda c: -g(c)

xinicial = 0

resultado = so.minimize(f, xinicial)
print(resultado)
maximo = resultado.x
print(maximo)
gmax = g(maximo)
print(gmax)

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: -0.3696348522521787
        x: [ 1.568e+00]
      nit: 5
      jac: [-1.565e-07]
 hess_inv: [[ 5.871e+00]]
     nfev: 12
     njev: 6
[1.56788847]
[0.36963485]


Questão 2.


In [ ]:
import numpy as np
import scipy.sparse.linalg as sp
import scipy.optimize as so

A = np.array([[3,1,0], [2,1,1], [0,2,5  ]])
b = np.array([[10],[9],[9]])
x = sp.cgs(A,b, [0,0,0], maxiter=4)

print("O resultado é: ", x[0])
print(x)

O resultado é:  [ 6. -8.  5.]
(array([ 6., -8.,  5.]), 0)


Questao 3.

In [ ]:
import numpy as np
import scipy.sparse.linalg as sp


A = np.array([[15, 17, 19],
              [0.30, 0.40, 0.55],
              [1.0, 1.2, 1.5]])

b = np.array([3890, 95, 282])

x = sp.cgs(A, b, [0, 0, 0])

print("Quantidade de componentes produzidos por dia:")
print(f"Componente 1: {x[0][0]:.4f}")
print(f"Componente 2: {x[0][1]:.4f}")
print(f"Componente 3: {x[0][2]:.4f}")
print(x)

Quantidade de componentes produzidos por dia:
Componente 1: 91.0843
Componente 2: 58.5718
Componente 3: 80.4224
(array([91.08425882, 58.5718016 , 80.42241441]), 0)


Questão 4.

In [ ]:
import numpy as np
import scipy.sparse.linalg as sp

L = np.array([[ 2, -1,  0, -1,  0],
              [-1,  3, -1, -1,  0],
              [ 0, -1,  1,  0,  0],
              [-1, -1,  0,  3, -1],
              [ 0,  0,  0, -1,  1]])

b = np.array([100, 0, -100, 0, 0], dtype=float)

x = sp.cgs(L, b, [0, 0, 0, 0, 0])

print("a) Fluxo (potencial de carga) nos bairros:")
bairros = ['A', 'B', 'C', 'D', 'E']
for i, nome in enumerate(bairros):
    print(f"  Bairro {nome}: {x[0][i]:.4f}")
print(x)

a) Fluxo (potencial de carga) nos bairros:
  Bairro A: 60.0000
  Bairro B: -6.6667
  Bairro C: -106.6667
  Bairro D: 26.6667
  Bairro E: 26.6667
(array([  60.        ,   -6.66666667, -106.66666667,   26.66666667,
         26.66666667]), 0)


Questão 5.

In [7]:
import numpy as np
import scipy.sparse.linalg as sp

L = np.array([[ 2, -1,  0, -1,  0],
              [-1,  3, -1, -1,  0],
              [ 0, -1,  1,  0,  0],
              [-1, -1,  0,  3, -1],
              [ 0,  0,  0, -1,  1]])

b_dobro = np.array([200, 0, -200, 0, 0], dtype=float)

x_dobro = sp.cgs(L, b_dobro, [0, 0, 0, 0, 0])

print("Fluxo com entrada dobrada em A:")
bairros = ['A', 'B', 'C', 'D', 'E']
for i, nome in enumerate(bairros):
    print(f"  Bairro {nome}: {x_dobro[0][i]:.4f}")
print("\nO fluxo em B dobra proporcionalmente ao dobro da entrada em A.")
print(x_dobro)

Fluxo com entrada dobrada em A:
  Bairro A: 120.0000
  Bairro B: -13.3333
  Bairro C: -213.3333
  Bairro D: 53.3333
  Bairro E: 53.3333

O fluxo em B dobra proporcionalmente ao dobro da entrada em A.
(array([ 120.        ,  -13.33333333, -213.33333333,   53.33333333,
         53.33333333]), 0)
