In [ ]:
import numpy.linalg as npl
import numpy as np

A = np.array(([15, -3, -1], [-3, 18, -6], [-4, -1, 12]))
b= np.array(([3800], [1200], [2350]))

I = npl.inv(A)

print("Matriz inversa ")
print(I)
print("Solução utilizando a matriz inversa ")
c = np.dot(I, b)
print("c = \n", c)

## x tem q dar 27,15 e 29,15%
x1 = I[0,0]*b[0] + I[0,1]*b[1] + I[0,2]*b[2]
novob3 = ((c[0]+10) -I[0,0]*b[0] - I[0,1]*b[1])/I[0,2]
x2 = I[1,0]*b[0] + I[1,1]*b[1] + I[1,2]*b[2]
x3 = I[2,0]*b[0] + I[2,1]*b[1] + I[2,2]*b[2]


print("\n")
print(novob3)
print(novob3/b[2])

Matriz inversa 
[[0.07253886 0.01278066 0.01243523]
 [0.02072539 0.06079447 0.03212435]
 [0.02590674 0.00932642 0.09015544]]
Solução utilizando a matriz inversa 
c = 
 [[320.20725389]
 [227.20207254]
 [321.50259067]]


[3154.16666667]
[1.34219858]


Aplicacao 2

In [37]:
import numpy.linalg as npl
import numpy as np

# Linhas = materiais (areia, cascalho fino, cascalho grosso)
# Colunas = minas (M1, M2, M3)
A = np.array([[0.52, 0.20, 0.25],
              [0.30, 0.50, 0.20],
              [0.18, 0.30, 0.55]])

b = np.array([[4800], [5810], [5690]])

I = npl.inv(A)

print("Matriz inversa:")
print(I)

y = np.dot(I, b)
print("\nO engenheiro deve retirar das Minas 1, 2 e 3, respectivamente (m³):")
print(y)

# --- Caso 1: Mina 2 extrai 1000 m³ a mais ---
# y[1] = I[1,0]*b[0] + I[1,1]*b[1] + I[1,2]*b[2]
# Queremos y[1] + 1000, variando só b[0] (areia)
novob1 = ((y[1] + 1000) - I[1,1]*b[1] - I[1,2]*b[2]) / I[1,0]
variacao1 = novob1 / b[0] - 1

print("\nSe retirarmos 1000 m³ a mais da Mina 2, a nova quantidade de areia será:")
print(novob1)
print("O percentual de variação foi de:")
print(variacao1)

# --- Caso 2: Mina 1 extrai 1000 m³ a mais ---
# y[0] = I[0,0]*b[0] + I[0,1]*b[1] + I[0,2]*b[2]
# Queremos y[0] + 1000, variando só b[0] (areia)
novob2 = ((y[0] + 1000) - I[0,1]*b[1] - I[0,2]*b[2]) / I[0,0]
variacao2 = novob2 / b[0] - 1

print("\nSe retirarmos 1000 m³ a mais da Mina 1, a nova quantidade de areia será:")
print(novob2)
print("O percentual de variação foi de:")
print(variacao2)

Matriz inversa:
[[ 2.50000000e+00 -4.06976744e-01 -9.88372093e-01]
 [-1.50000000e+00  2.80232558e+00 -3.37209302e-01]
 [ 4.76661048e-17 -1.39534884e+00  2.32558140e+00]]

O engenheiro deve retirar das Minas 1, 2 e 3, respectivamente (m³):
[[4011.62790698]
 [7162.79069767]
 [5125.58139535]]

Se retirarmos 1000 m³ a mais da Mina 2, a nova quantidade de areia será:
[4133.33333333]
O percentual de variação foi de:
[-0.13888889]

Se retirarmos 1000 m³ a mais da Mina 1, a nova quantidade de areia será:
[5200.]
O percentual de variação foi de:
[0.08333333]
